name: Monitor GitLab Tag and Create Alpha Release

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour. Adjust as needed (e.g., '0 0 * * *' for daily at midnight UTC)
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  check-and-release:
    runs-on: ubuntu-latest # Uses a GitHub-hosted runner with Ubuntu
    container: clickable/ci-20.04-arm64 # Specifies the Docker image for the job to run inside

    # Permissions required for creating releases and tags in your repository
    permissions:
      contents: write # Needed for softprops/action-gh-release to create releases and push tags

    steps:
      - name: Install Utilities (jq, curl)
        run: |
          apt-get update
          apt-get install -y jq curl

      - name: Get latest GitLab release tag (Following Redirects)
        id: get_gitlab_tag # Assigns an ID to this step to access its outputs later
        run: |
          # The project ID for librewolf-community/browser/appimage
          GITLAB_PROJECT_ID="24386000"
          GITLAB_PERMALINK_URL="https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/releases/permalink/latest"

          echo "Attempting to fetch latest GitLab release tag via permalink and follow redirects from: $GITLAB_PERMALINK_URL"

          EFFECTIVE_URL=$(curl -s -L -o /dev/null -w '%{url_effective}' "$GITLAB_PERMALINK_URL")

          echo "Effective (redirected) URL: $EFFECTIVE_URL"

          if [ -z "$EFFECTIVE_URL" ]; then
            echo "Error: Could not retrieve effective URL from GitLab permalink. No redirect happened or curl failed."
            echo "gitlab_tag=v0.0.0" >> $GITHUB_OUTPUT # Set a safe baseline tag
            exit 0 # Exit gracefully if no URL, but allow workflow to continue with baseline
          fi

          GITLAB_TAG=$(basename "$EFFECTIVE_URL")

          if [ -z "$GITLAB_TAG" ]; then
            echo "Error: Could not extract tag from the effective URL: $EFFECTIVE_URL"
            echo "gitlab_tag=v0.0.0" >> $GITHUB_OUTPUT # Set a safe baseline
          else
            echo "Latest GitLab Tag (LibreWolf version): $GITLAB_TAG"
            echo "gitlab_tag=$GITLAB_TAG" >> $GITHUB_OUTPUT
          fi

      - name: Get latest GitHub release tag from this repo
        id: get_github_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
        run: |
          GITHUB_API_URL="https://api.github.com/repos/${{ github.repository }}/releases/latest"

          echo "Fetching latest GitHub release from: $GITHUB_API_URL"
          GITHUB_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$GITHUB_API_URL")

          if echo "$GITHUB_RESPONSE" | jq -e 'has("message") and .message == "Not Found"' >/dev/null; then
            echo "No existing GitHub releases found in this repository."
            LATEST_GITHUB_TAG="v0.0.0" # Set a baseline for comparison
          else
            LATEST_GITHUB_TAG=$(echo "$GITHUB_RESPONSE" | jq -r '.tag_name // empty')
            if [ -z "$LATEST_GITHUB_TAG" ]; then
              echo "Error: Could not extract tag_name from GitHub API response. Assuming v0.0.0"
              echo "Response: $GITHUB_RESPONSE"
              LATEST_GITHUB_TAG="v0.0.0" # Fallback
            fi
          fi

          echo "Latest GitHub Tag (our app version): $LATEST_GITHUB_TAG"
          echo "github_tag=$LATEST_GITHUB_TAG" >> $GITHUB_OUTPUT

      - name: Checkout repository and submodules
        # Checkout unconditionally now, as we need manifest.json for versioning
        # We'll still use the 'compare_versions' to decide if to build/release
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensures Git submodules are initialized and updated

      - name: Get App Version from manifest.json
        id: get_app_version
        run: |
          # Assuming manifest.json is in the root of the checked-out repository
          if [ -f manifest.json ]; then
            APP_VERSION=$(jq -r '.version' manifest.json)
            if [ -z "$APP_VERSION" ] || [ "$APP_VERSION" == "null" ]; then
              echo "Warning: Could not extract version from manifest.json. Defaulting to 0.0.0."
              APP_VERSION="0.0.0"
            fi
            echo "Extracted App Version from manifest.json: $APP_VERSION"
          else
            echo "Error: manifest.json not found in repository root. Defaulting to 0.0.0."
            APP_VERSION="0.0.0"
          fi
          echo "app_version=v$APP_VERSION" >> $GITHUB_OUTPUT # Add 'v' prefix for semantic versioning consistency

      - name: Compare versions and determine if build is needed
        id: compare_versions
        run: |
          GITLAB_TAG="${{ steps.get_gitlab_tag.outputs.gitlab_tag }}"
          GITHUB_TAG="${{ steps.get_github_tag.outputs.github_tag }}"
          APP_VERSION_TAG="${{ steps.get_app_version.outputs.app_version }}" # Our app version with 'v' prefix

          echo "Comparing LibreWolf Tag ($GITLAB_TAG) with Last Released App Tag ($GITHUB_TAG)"
          echo "Current App Version from manifest.json: $APP_VERSION_TAG"

          # Ensure tags are not empty before semantic version comparison
          if [ -z "$GITLAB_TAG" ]; then GITLAB_TAG="v0.0.0"; fi
          if [ -z "$GITHUB_TAG" ]; then GITHUB_TAG="v0.0.0"; fi
          if [ -z "$APP_VERSION_TAG" ]; then APP_VERSION_TAG="v0.0.0"; fi

          # We have two criteria for a new build/release:
          # 1. A newer LibreWolf tag (GITLAB_TAG)
          # 2. Our local app version (APP_VERSION_TAG) has not been released yet
          
          # Check for new LibreWolf version (primary trigger)
          HIGHEST_LIBREWOLF_TAG=$(printf "%s\n%s" "$GITLAB_TAG" "$GITHUB_TAG" | sort -V | tail -n 1)
          NEW_LIBREWOLF_AVAILABLE=false
          if [ "$GITLAB_TAG" = "$HIGHEST_LIBREWOLF_TAG" ] && [ "$GITLAB_TAG" != "$GITHUB_TAG" ]; then
            NEW_LIBREWOLF_AVAILABLE=true
            echo "Condition 1: Newer LibreWolf tag detected: $GITLAB_TAG"
          else
            echo "Condition 1: No newer LibreWolf tag ($GITLAB_TAG) compared to current GitHub tag ($GITHUB_TAG)."
          fi

          # Check if our current app version is already released
          # This assumes GITHUB_TAG is the app version of the last release
          APP_VERSION_ALREADY_RELEASED=false
          if [ "$APP_VERSION_TAG" = "$GITHUB_TAG" ]; then
              APP_VERSION_ALREADY_RELEASED=true
              echo "Condition 2: App version ($APP_VERSION_TAG) is already released."
          else
              echo "Condition 2: App version ($APP_VERSION_TAG) is different from last released ($GITHUB_TAG)."
          fi
          
          # Decide whether to run based on either condition
          # We want to build if a NEW LibreWolf version is available OR if our current app version hasn't been released yet (e.g. manual update)
          if [ "$NEW_LIBREWOLF_AVAILABLE" = "true" ] || [ "$APP_VERSION_ALREADY_RELEASED" = "false" ]; then
            echo "Initiating build and release due to new LibreWolf version or unreleased app version."
            echo "run_clickable=true" >> $GITHUB_OUTPUT
            echo "new_release_tag=$APP_VERSION_TAG" >> $GITHUB_OUTPUT # The release tag will be our app version
          else
            echo "No new LibreWolf version and current app version is already released. Skipping build."
            echo "run_clickable=false" >> $GITHUB_OUTPUT
          fi


      - name: Build Click package for arm64
        if: steps.compare_versions.outputs.run_clickable == 'true'
        run: clickable build --arch arm64 --skip-review

      - name: Upload Click package artifacts (for workflow run)
        if: steps.compare_versions.outputs.run_clickable == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: click-packages-arm64-${{ steps.compare_versions.outputs.new_release_tag }}
          path: build/*/app/*.click
          retention-days: 7

      - name: Create Alpha Release
        if: steps.compare_versions.outputs.run_clickable == 'true'
        uses: softprops/action-gh-release@v2
        with:
          # Release tag will be our app's version (e.g., v0.2.3)
          tag_name: ${{ steps.compare_versions.outputs.new_release_tag }}
          # Release name will be "Alpha <app_version>"
          name: Alpha ${{ steps.compare_versions.outputs.new_release_tag }}
          body: | # Markdown content for the release description
            Automated **Alpha Release** for version `${{ steps.compare_versions.outputs.new_release_tag }}`.
            
            This build is based on **LibreWolf version**: `${{ steps.get_gitlab_tag.outputs.gitlab_tag }}`.
            
            This is an automated build and may contain the latest changes.
            
            ---
            *Built by GitHub Actions*
          prerelease: true # Marks this as a pre-release (suitable for 'alpha')
          draft: false # Set to true if you want to review and publish manually
          files: build/*/app/*.click # Attaches the generated .click files as release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}