name: Monitor LibreWolf and Create Release

on:
  schedule:
    - cron: '0 0 */3 * *' # Runs every 3 days at midnight (00:00) UTC
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  check-and-release:
    runs-on: ubuntu-latest # Uses a GitHub-hosted runner with Ubuntu
    container: clickable/ci-20.04-arm64 # Specifies the Docker image for the job to run inside

    # Permissions required for creating releases and tags, AND pushing back to repo (if auto-increment is used)
    permissions:
      contents: write # Needed for softprops/action-gh-release AND for git push (if manifest is updated)

    steps:
      - name: Install Utilities (jq, curl, git)
        run: |
          apt-get update
          apt-get install -y jq curl git

      - name: Configure Git for Auto-Commit
        # This is necessary if we're going to push changes back to the repo (e.g., auto-increment manifest.json)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout repository and submodules
        # We need to checkout unconditionally because we always read manifest.json and .last_librewolf_tag
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }} # Needed for pushing back changes

      - name: Get latest LibreWolf tag from GitLab (Following Redirects)
        id: get_gitlab_tag
        run: |
          # Enable strict error checking and command tracing for debugging
          set -eux

          GITLAB_PROJECT_ID="24386000"
          GITLAB_PERMALINK_URL="https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/releases/permalink/latest"

          echo "Attempting to fetch latest LibreWolf tag via permalink: $GITLAB_PERMALINK_URL"
          EFFECTIVE_URL=$(curl -s -L -o /dev/null -w '%{url_effective}' "$GITLAB_PERMALINK_URL")
          echo "Effective (redirected) URL: $EFFECTIVE_URL"

          if [ -z "$EFFECTIVE_URL" ]; then
            echo "Error: Could not retrieve effective URL from GitLab permalink. No redirect happened or curl failed."
            echo "gitlab_tag=v0.0.0" >> "$GITHUB_OUTPUT"
            # We don't exit 0 here, because if there's an error getting the tag, we still want to try building
            # based on other conditions or proceed with a default. Let determine_release_info handle the build decision.
          else
            # Extract the LibreWolf tag (e.g., v138.0.4-1)
            GITLAB_TAG=$(basename "$EFFECTIVE_URL")
            if [ -z "$GITLAB_TAG" ]; then
              echo "Error: Could not extract tag from the effective URL: $EFFECTIVE_URL"
              echo "gitlab_tag=v0.0.0" >> "$GITHUB_OUTPUT"
            else
              echo "Latest LibreWolf Tag: $GITLAB_TAG"
              echo "gitlab_tag=$GITLAB_TAG" >> "$GITHUB_OUTPUT"
            fi
          fi

      - name: Get Last Processed LibreWolf Tag (from .last_librewolf_tag file)
        id: get_last_processed_lw_tag
        run: |
          set -eux
          LAST_PROCESSED_LW_TAG="v0.0.0"
          if [ -f .last_librewolf_tag ]; then
            LAST_PROCESSED_LW_TAG=$(cat .last_librewolf_tag | tr -d '\n') # Remove newline
            echo "Found .last_librewolf_tag file: $LAST_PROCESSED_LW_TAG"
          else
            echo "No .last_librewolf_tag file found. Initializing to v0.0.0"
          fi
          echo "last_processed_lw_tag=$LAST_PROCESSED_LW_TAG" >> "$GITHUB_OUTPUT"

      - name: Get Latest uWolf App Tag from GitHub Releases
        id: get_github_app_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          GITHUB_API_URL="https://api.github.com/repos/${{ github.repository }}/releases/latest"
          echo "Fetching latest uWolf app release tag from: $GITHUB_API_URL"
          GITHUB_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$GITHUB_API_URL")

          LATEST_GITHUB_APP_TAG="v0.0.0" # Default baseline

          if echo "$GITHUB_RESPONSE" | jq -e 'has("message") and .message == "Not Found"' >/dev/null; then
            echo "No existing GitHub releases found in this repository."
          else
            LATEST_GITHUB_APP_TAG=$(echo "$GITHUB_RESPONSE" | jq -r '.tag_name // empty')
            if [ -z "$LATEST_GITHUB_APP_TAG" ]; then LATEST_GITHUB_APP_TAG="v0.0.0"; fi
          fi
          echo "Latest GitHub uWolf App Release Tag: $LATEST_GITHUB_APP_TAG"
          echo "github_app_tag=$LATEST_GITHUB_APP_TAG" >> "$GITHUB_OUTPUT"

      - name: Get Current uWolf App Version from manifest.json
        id: get_current_app_version
        run: |
          set -eux
          CURRENT_APP_VERSION="0.0.0" # Default baseline
          if [ -f manifest.json ]; then
            CURRENT_APP_VERSION=$(jq -r '.version' manifest.json)
            if [ -z "$CURRENT_APP_VERSION" ] || [ "$CURRENT_APP_VERSION" = "null" ]; then
              echo "Warning: Could not extract version from manifest.json. Defaulting to 0.0.0."
              CURRENT_APP_VERSION="0.0.0"
            fi
            echo "Current uWolf App Version from manifest.json: $CURRENT_APP_VERSION"
          else
            echo "Error: manifest.json not found in repository root. Defaulting to 0.0.0."
            CURRENT_APP_VERSION="0.0.0"
          fi
          echo "current_app_version=$CURRENT_APP_VERSION" >> "$GITHUB_OUTPUT"

      - name: Determine New Release Version and Build Trigger
        id: determine_build_info
        run: |
          # Enable strict error checking and command tracing for debugging
          set -eux # Keep set -eux for debugging, remove -o pipefail and here strings

          GITLAB_TAG="${{ steps.get_gitlab_tag.outputs.gitlab_tag }}"
          LAST_PROCESSED_LW_TAG="${{ steps.get_last_processed_lw_tag.outputs.last_processed_lw_tag }}"
          LAST_RELEASED_APP_TAG="${{ steps.get_github_app_tag.outputs.github_app_tag }}"
          CURRENT_APP_VERSION_RAW="${{ steps.get_current_app_version.outputs.current_app_version }}"
          CURRENT_APP_VERSION_WITH_V="v$CURRENT_APP_VERSION_RAW"

          NEW_UWOOLF_APP_VERSION_RAW="$CURRENT_APP_VERSION_RAW" # Proposed new version for manifest.json
          SHOULD_BUILD_FLAG=0 # 0 for false, 1 for true
          COMMIT_REQUIRED_FLAG=0 # 0 for false, 1 for true

          echo "Incoming LibreWolf Tag: $GITLAB_TAG"
          echo "Last Processed LibreWolf Tag: $LAST_PROCESSED_LW_TAG"
          echo "Current uWolf App Version (from manifest): $CURRENT_APP_VERSION_WITH_V"
          echo "Last Released uWolf App Tag (from GitHub releases): $LAST_RELEASED_APP_TAG"

          # Ensure tags are not empty for comparison (already handled by defaults, but defensive)
          [ -z "$GITLAB_TAG" ] && GITLAB_TAG="v0.0.0"
          [ -z "$LAST_PROCESSED_LW_TAG" ] && LAST_PROCESSED_LW_TAG="v0.0.0"
          [ -z "$LAST_RELEASED_APP_TAG" ] && LAST_RELEASED_APP_TAG="v0.0.0"
          [ -z "$CURRENT_APP_VERSION_WITH_V" ] && CURRENT_APP_VERSION_WITH_V="v0.0.0"

          # Condition 1: Compare LibreWolf tag with the last *processed* LibreWolf tag
          # If different, we should build.
          NEWER_LIBREWOLF_AVAILABLE_FLAG=0
          HIGHEST_LW_OF_TWO=$(printf "%s\n%s" "$LAST_PROCESSED_LW_TAG" "$GITLAB_TAG" | sort -V | tail -n 1)
          if [ "$GITLAB_TAG" = "$HIGHEST_LW_OF_TWO" ] && [ "$GITLAB_TAG" != "$LAST_PROCESSED_LW_TAG" ]; then
              NEWER_LIBREWOLF_AVAILABLE_FLAG=1
              echo "Condition 1: Newer LibreWolf upstream version detected: $GITLAB_TAG"
          else
              echo "Condition 1: No newer LibreWolf upstream."
          fi

          # Condition 2: Compare manifest.json version to latest released uWolf tag
          # If different, we should build (manual manifest update).
          UWOOLF_MANIFEST_VERSION_UPDATED_FLAG=0
          if [ "$CURRENT_APP_VERSION_WITH_V" != "$LAST_RELEASED_APP_TAG" ]; then
            UWOOLF_MANIFEST_VERSION_UPDATED_FLAG=1
            echo "Condition 2: Current uWolf App Version in manifest.json ($CURRENT_APP_VERSION_WITH_V) differs from last released ($LAST_RELEASED_APP_TAG)."
          else
            echo "Condition 2: Current uWolf App Version is same as last released."
          fi

          # Decision Logic for SHOULD_BUILD_FLAG and NEW_UWOOLF_APP_VERSION_RAW
          if [ "$NEWER_LIBREWOLF_AVAILABLE_FLAG" -eq 1 ]; then
            SHOULD_BUILD_FLAG=1
            echo "Reason to build: Newer LibreWolf version is available ($GITLAB_TAG)."
            # If current app version in manifest is the same as the last *released* app tag,
            # this means we need to increment the patch to make a new unique release.
            if [ "$CURRENT_APP_VERSION_WITH_V" = "$LAST_RELEASED_APP_TAG" ]; then
              echo "  Current uWolf App Version ($CURRENT_APP_VERSION_WITH_V) is already used for a release."
              echo "  Incrementing patch for a new build based on LibreWolf update."
              # POSIX-compliant way to read version components
              echo "$CURRENT_APP_VERSION_RAW" | IFS='.' read -r MAJOR MINOR PATCH
              NEW_PATCH=$((PATCH + 1))
              NEW_UWOOLF_APP_VERSION_RAW="$MAJOR.$MINOR.$NEW_PATCH"
              COMMIT_REQUIRED_FLAG=1 # Need to commit manifest.json change
              echo "  New proposed uWolf App Version (raw): $NEW_UWOOLF_APP_VERSION_RAW"
            else
              echo "  Current uWolf App Version ($CURRENT_APP_VERSION_WITH_V) was manually updated. No patch increment needed."
              # Use the current manifest version as is.
            fi
          elif [ "$UWOOLF_MANIFEST_VERSION_UPDATED_FLAG" -eq 1 ]; then
            SHOULD_BUILD_FLAG=1
            echo "Reason to build: uWolf manifest.json version was manually updated ($CURRENT_APP_VERSION_WITH_V)."
            # No patch increment here, use the version from manifest.json as is.
          else
            echo "No reason to build: No new LibreWolf, and current uWolf App Version is already released."
          fi

          echo "Final Decision - Should Build: $( [ "$SHOULD_BUILD_FLAG" -eq 1 ] && echo "true" || echo "false" )"
          echo "Final Proposed uWolf App Version (raw): $NEW_UWOOLF_APP_VERSION_RAW"
          echo "Commit manifest.json and .last_librewolf_tag required: $( [ "$COMMIT_REQUIRED_FLAG" -eq 1 ] && echo "true" || echo "false" )"

          # Set outputs for subsequent steps
          echo "run_clickable=$( [ "$SHOULD_BUILD_FLAG" -eq 1 ] && echo "true" || echo "false" )" >> "$GITHUB_OUTPUT"
          echo "new_uwolf_app_version_tag=v$NEW_UWOOLF_APP_VERSION_RAW" >> "$GITHUB_OUTPUT"
          echo "commit_required=$( [ "$COMMIT_REQUIRED_FLAG" -eq 1 ] && echo "true" || echo "false" )" >> "$GITHUB_OUTPUT"
          echo "current_lw_tag_for_this_build=$GITLAB_TAG" >> "$GITHUB_OUTPUT"

      # This is the debug step to confirm outputs seen by GitHub Actions
      - name: Debug Workflow Outputs
        run: |
          echo "Debugging outputs from determine_build_info step:"
          echo "run_clickable: ${{ steps.determine_build_info.outputs.run_clickable }}"
          echo "new_uwolf_app_version_tag: ${{ steps.determine_build_info.outputs.new_uwolf_app_version_tag }}"
          echo "commit_required: ${{ steps.determine_build_info.outputs.commit_required }}"
          echo "current_lw_tag_for_this_build: ${{ steps.determine_build_info.outputs.current_lw_tag_for_this_build }}"
          echo "--- End Debug ---"

      - name: Update manifest.json and .last_librewolf_tag file (if required)
        # This step runs if a build is triggered OR if a manifest commit is required (e.g., patch increment)
        if: ${{ steps.determine_build_info.outputs.commit_required == 'true' || steps.determine_build_info.outputs.run_clickable == 'true' }}
        run: |
          set -eux # For debugging this step too

          NEW_UWOOLF_APP_VERSION_RAW="${{ steps.determine_build_info.outputs.new_uwolf_app_version_tag }}"
          # Remove 'v' prefix if it exists, as manifest.json typically uses "X.Y.Z"
          NEW_UWOOLF_APP_VERSION_MANIFEST="${NEW_UWOOLF_APP_VERSION_RAW#v}" 
          CURRENT_LW_TAG_FOR_THIS_BUILD="${{ steps.determine_build_info.outputs.current_lw_tag_for_this_build }}"

          # Update manifest.json only if an increment happened
          if [ "${{ steps.determine_build_info.outputs.commit_required }}" = "true" ]; then
            echo "Updating manifest.json to version $NEW_UWOOLF_APP_VERSION_MANIFEST"
            jq ".version = \"$NEW_UWOOLF_APP_VERSION_MANIFEST\"" manifest.json > manifest.json.tmp && mv manifest.json.tmp manifest.json
            git add manifest.json
          else
            echo "No manifest.json version update required (commit_required was false)."
          fi

          # Always update .last_librewolf_tag if we are building/releasing (even if no manifest commit)
          echo "Updating .last_librewolf_tag to $CURRENT_LW_TAG_FOR_THIS_BUILD"
          echo "$CURRENT_LW_TAG_FOR_THIS_BUILD" > .last_librewolf_tag
          git add .last_librewolf_tag

          # Only commit and push if there are changes to commit
          if ! git diff --quiet --exit-code; then # Check if there are any uncommitted changes at all
            echo "Changes detected. Committing now."
            # Use the actual new version from the manifest (or the one determined for commit)
            git commit -am "chore: Automated update for uWolf version to $NEW_UWOOLF_APP_VERSION_MANIFEST (LibreWolf $CURRENT_LW_TAG_FOR_THIS_BUILD)"
            git push origin HEAD:${{ github.ref_name }} # Push to the current branch
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Click package for arm64
        if: ${{ steps.determine_build_info.outputs.run_clickable == 'true' }}
        run: clickable build --arch arm64 --skip-review

      - name: Upload Click package artifacts (for workflow run)
        if: ${{ steps.determine_build_info.outputs.run_clickable == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: click-packages-arm64-${{ steps.determine_build_info.outputs.new_uwolf_app_version_tag }}
          path: build/*/app/*.click
          retention-days: 7

      - name: Create Alpha Release
        if: ${{ steps.determine_build_info.outputs.run_clickable == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.determine_build_info.outputs.new_uwolf_app_version_tag }}
          name: Alpha uWolf ${{ steps.determine_build_info.outputs.new_uwolf_app_version_tag }}
          body: |
            Automated **Alpha Release** for uWolf version `${{ steps.determine_build_info.outputs.new_uwolf_app_version_tag }}`.
            
            This build is based on **LibreWolf version**: `${{ steps.get_gitlab_tag.outputs.gitlab_tag }}`.
            
            ---
            *Built by GitHub Actions*
          prerelease: true
          draft: false
          files: build/*/app/*.click
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Secondary LibreWolf Tag
        if: ${{ steps.determine_build_info.outputs.run_clickable == 'true' }}
        run: |
          set -eux # For debugging this step too
          LIBREWOLF_TAG="${{ steps.get_gitlab_tag.outputs.gitlab_tag }}"
          
          echo "Creating secondary Git tag for LibreWolf version: $LIBREWOLF_TAG"
          # Ensure the tag is not empty AND doesn't already exist
          if [ -n "$LIBREWOLF_TAG" ] && ! git rev-parse --verify "refs/tags/$LIBREWOLF_TAG" >/dev/null 2>&1; then
            git tag "$LIBREWOLF_TAG"
            git push origin "refs/tags/$LIBREWOLF_TAG"
          else
            echo "Git tag $LIBREWOLF_TAG already exists or is empty. Skipping creation."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}